### ISSUE TITLE
캐릭터창 변경하는거 누르면 떠요

### ISSUE THREAD

**Issue by whirea** [nemi-dev/dfm-view#2]
이런! 선택창이 고장나버렸어요! 어서 개발자에게 알려주세요!
오류 이름 : TypeError
오류 메시지 : Cannot read properties of undefined (reading 'dfclass')
오류 스택 : TypeError: Cannot read properties of undefined (reading 'dfclass') at https://dfm.nemi.ml/assets/view-d757af0f.js:2:22243 at https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:16386 at l (https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:15340) at https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:16518 at l (https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:15340) at https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:16484 at l (https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:15340) at https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:16484 at l (https://dfm.nemi.ml/assets/redux-b7e888c1.js:1:15340) at https://dfm.nemi.ml/assets/view-d757af0f.js:583:75

**Comment by whirea** [comment]
![image](https://github.com/nemi-dev/dfm-view/assets/26585918/63bc2176-beed-4ca4-927a-55ab02b7d647)

**Comment by nemi-dev** [comment]
저장된 캐릭터 선택창 진입시 고장나는 버그를 해결했습니다. 현재는 정상 작동하는지 확인해주시기 바랍니다.

**Comment by whirea** [comment]
정상입니다

**Comment by nemi-dev** [comment]
답변 감사합니다. 이외에도 문의사항 있으면 언제든 남겨주세요.
